#!/bin/bash

echo "🏗️ Bros Enterprises - Hardware Store Website Demo"
echo "================================================"
echo ""

# Check if servers are running
if ! curl -s http://localhost:3000 > /dev/null 2>&1; then
    echo "❌ Frontend not running. Starting servers..."
    ./scripts/start-dev.sh &
    sleep 10
fi

echo "🎯 BROS ENTERPRISES HARDWARE STORE FEATURES:"
echo ""

echo "🏠 HOME PAGE:"
echo "   • Professional hardware store branding"
echo "   • Complete product showcase (Paints, Hardware, Sanitary, Electricals)"
echo "   • Store location and contact information"
echo "   • Service highlights and company values"
echo "   • Located in Gurugram with professional presentation"
echo "   🌐 Visit: http://localhost:3000"
echo ""

echo "🎨 PAINTS SECTION:"
echo "   • Interior & Exterior paints showcase"
echo "   • Premium paint brands (Asian Paints, Berger, Nerolac, etc.)"
echo "   • Paint categories with features and benefits"
echo "   • Color consultation and matching services"
echo "   • Professional paint advice and guidance"
echo "   🌐 Visit: http://localhost:3000/paints"
echo ""

echo "🔧 HARDWARE SECTION:"
echo "   • Construction tools and building materials"
echo "   • Professional-grade hardware products"
echo "   • Tool brands (Bosch, Makita, DeWalt, Stanley, etc.)"
echo "   • Fasteners, fittings, and accessories"
echo "   • Technical consultation and support"
echo "   🌐 Visit: http://localhost:3000/hardware"
echo ""

echo "🚿 SANITARY WARE SECTION:"
echo "   • Modern bathroom and kitchen fixtures"
echo "   • Premium sanitary brands (Kohler, Jaquar, Hindware, etc.)"
echo "   • Faucets, sinks, and bathroom accessories"
echo "   • Design consultation and installation guidance"
echo "   • Complete bathroom solutions"
echo "   🌐 Visit: http://localhost:3000/sanitary"
echo ""

echo "⚡ ELECTRICALS SECTION:"
echo "   • Electrical wiring and safety equipment"
echo "   • Trusted electrical brands (Havells, Anchor, Legrand, etc.)"
echo "   • Switches, sockets, and lighting solutions"
echo "   • Safety-certified electrical products"
echo "   • Electrical consultation and support"
echo "   🌐 Visit: http://localhost:3000/electricals"
echo ""

echo "ℹ️ ABOUT US PAGE:"
echo "   • Company history and story since 2010"
echo "   • Core values and commitment to quality"
echo "   • Timeline of business milestones"
echo "   • Store location and contact details"
echo "   • Professional business presentation"
echo "   🌐 Visit: http://localhost:3000/about"
echo ""

echo "📞 CONTACT PAGE:"
echo "   • Store location in Gurugram"
echo "   • Contact form for inquiries"
echo "   • Business hours and store information"
echo "   • Phone and email contact options"
echo "   • Professional customer service"
echo "   🌐 Visit: http://localhost:3000/contact"
echo ""

echo "🎨 DESIGN HIGHLIGHTS:"
echo "   • Professional hardware store color scheme"
echo "   • Orange primary color (#FF6B35) for construction theme"
echo "   • Green secondary color (#2E7D32) for trust and reliability"
echo "   • Clean, modern typography with Roboto font"
echo "   • Responsive design for all devices"
echo "   • Professional business presentation"
echo ""

echo "🏪 BUSINESS FEATURES:"
echo "   • Complete product categorization"
echo "   • Brand showcases for each category"
echo "   • Service descriptions and offerings"
echo "   • Professional store information"
echo "   • Contact and location details"
echo "   • Expert consultation services"
echo ""

echo "🔧 TECHNICAL FEATURES:"
echo "   • Material-UI with custom hardware theme"
echo "   • Dark/Light mode toggle"
echo "   • TypeScript for type safety"
echo "   • Responsive grid layouts"
echo "   • Professional component library"
echo "   • SEO-friendly structure"
echo ""

echo "🚀 DEMO WALKTHROUGH:"
echo "1. Visit http://localhost:3000 for the homepage"
echo "2. Explore each product category (Paints, Hardware, Sanitary, Electricals)"
echo "3. Check the About Us page for company information"
echo "4. Use the Contact page for store details and inquiries"
echo "5. Try the dark/light theme toggle in the header"
echo "6. Test the responsive design on different screen sizes"
echo ""

echo "💡 BUSINESS HIGHLIGHTS:"
echo "   • One-stop store for all building materials"
echo "   • Located in the heart of Gurugram"
echo "   • High-quality products from trusted brands"
echo "   • Expert consultation and customer service"
echo "   • Professional business presentation"
echo ""

echo "🌐 Application URLs:"
echo "   Hardware Store Website: http://localhost:3000"
echo "   Backend API: http://localhost:5000/api"
echo "   Health Check: http://localhost:5000/health"
echo ""

echo "📚 Documentation:"
echo "   Deployment Guide: ./docs/deployment.md"
echo "   Troubleshooting: ./docs/troubleshooting.md"
echo "   GitHub Repo: https://github.com/shushi3101/BrosEnterpriseWebApp"
echo ""

echo "✅ Bros Enterprises hardware store website is ready!"
echo "🎉 Professional business website for building materials store in Gurugram!"
