name: 🚀 Simple Deploy (Backup)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
    
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: 🔧 Install and build
      run: |
        # Use our build script
        chmod +x build.sh
        ./build.sh
    
    - name: 📤 Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend/dist
    
    - name: 🚀 Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
